<script setup lang="ts">
definePageMeta({ middleware:'admin' })
const route=useRoute(); const supabase=useSupabaseClient(); const event=ref<any>(null); const students=ref<any[]>([]); const participants=ref<any[]>([]); const search=ref(''); const houseFilter=ref(''); const selected=ref<string[]>([]); const houses=ref<any[]>([]); const message=ref(''); const errorMessage=ref(''); const saving=ref(false)
const participantIds=computed(()=>new Set(participants.value.map(p=>p.student_id)))
const availableStudents=computed(()=>students.value.filter(s=>!participantIds.value.has(s.id)).filter(s=>{const q=search.value.trim().toLowerCase(); return (!q||`${s.first_name} ${s.last_name} ${s.student_number||''}`.toLowerCase().includes(q))&&(!houseFilter.value||String(s.house_id||'')===houseFilter.value)}))
const load=async()=>{const id=Number(route.params.id);const [e,s,p,h]=await Promise.all([supabase.from('events').select('*,sport:sports(name,measurement_type),teacher:profiles!events_teacher_id_fkey(first_name,last_name)').eq('id',id).single(),supabase.from('profiles').select('id,first_name,last_name,student_number,year_level,house_id,house:houses(name,colour)').eq('role','student').eq('active',true).order('last_name'),supabase.from('event_participants').select('id,event_id,student_id,lane,bib_number,student:profiles(first_name,last_name,student_number,house:houses(name,colour))').eq('event_id',id).order('lane'),supabase.from('houses').select('id,name').eq('active',true).order('name')]);event.value=e.data;students.value=(s.data||[]).filter((x:any)=>!e.data?.year_level||x.year_level===e.data.year_level);participants.value=p.data||[];houses.value=h.data||[]}
const addSelected=async()=>{if(!selected.value.length)return;saving.value=true;errorMessage.value='';const maxLane=Math.max(0,...participants.value.map(p=>Number(p.lane)||0));const inserts=selected.value.map((id,i)=>({event_id:Number(route.params.id),student_id:id,lane:maxLane+i+1}));const{error}=await supabase.from('event_participants').insert(inserts);if(error)errorMessage.value=error.message;else{message.value=`Added ${inserts.length} student${inserts.length===1?'':'s'} to the event.`;selected.value=[];await load()}saving.value=false}
const removeParticipant=async(p:any)=>{if(!confirm(`Remove ${p.student?.first_name} ${p.student?.last_name} from this event?`))return;const{error}=await supabase.from('event_participants').delete().eq('id',p.id);if(error)errorMessage.value=error.message;else await load()}
const saveParticipant=async(p:any)=>{const{error}=await supabase.from('event_participants').update({lane:p.lane||null,bib_number:p.bib_number||null}).eq('id',p.id);if(error)errorMessage.value=error.message;else message.value='Event assignment updated.'}
const selectAllVisible=()=>{selected.value=availableStudents.value.map(s=>s.id)}
onMounted(load)
</script>
<template><main class="mx-auto max-w-7xl px-4 py-8"><NuxtLink to="/admin/events" class="text-sm font-semibold text-blue-600">← Events</NuxtLink><div v-if="event"><div class="mt-3 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-3xl font-bold">Assign Students</h1><p class="mt-1 text-slate-500">{{event.name}} · {{event.sport?.name}} · {{event.event_date}}</p></div><NuxtLink :to="`/teacher/events/${event.id}`" class="rounded-lg bg-emerald-600 px-4 py-2 text-center font-semibold text-white">Open Result Entry</NuxtLink></div><div v-if="message" class="mt-5 rounded-lg bg-emerald-50 p-3 text-emerald-700">{{message}}</div><div v-if="errorMessage" class="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{{errorMessage}}</div>
<section class="mt-6 rounded-xl border bg-white p-5"><div class="flex items-center justify-between"><div><h2 class="text-lg font-bold">Assigned Students ({{participants.length}})</h2><p class="text-sm text-slate-500">Set lanes or bib numbers before the event.</p></div></div><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead class="bg-slate-50"><tr><th class="p-3">Student</th><th>House</th><th>Lane</th><th>Bib</th><th></th></tr></thead><tbody><tr v-for="p in participants" :key="p.id" class="border-t"><td class="p-3 font-semibold">{{p.student?.last_name}}, {{p.student?.first_name}}</td><td>{{p.student?.house?.name||'—'}}</td><td><input v-model.number="p.lane" type="number" min="1" class="w-20 rounded border px-2 py-1"></td><td><input v-model="p.bib_number" class="w-28 rounded border px-2 py-1"></td><td class="space-x-2"><button class="rounded bg-blue-600 px-3 py-1.5 text-sm font-semibold text-white" @click="saveParticipant(p)">Save</button><button class="rounded bg-red-50 px-3 py-1.5 text-sm font-semibold text-red-700" @click="removeParticipant(p)">Remove</button></td></tr><tr v-if="!participants.length"><td colspan="5" class="p-8 text-center text-slate-500">No students assigned yet.</td></tr></tbody></table></div></section>
<section class="mt-6 rounded-xl border bg-white p-5"><div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 class="text-lg font-bold">Available Students</h2><p class="text-sm text-slate-500">{{event.year_level?`Showing Year ${event.year_level} students`:'Showing all active students'}}</p></div><div class="flex flex-col gap-2 sm:flex-row"><input v-model="search" placeholder="Search…" class="rounded-lg border px-3 py-2"><select v-model="houseFilter" class="rounded-lg border px-3 py-2"><option value="">All houses</option><option v-for="h in houses" :key="h.id" :value="String(h.id)">{{h.name}}</option></select></div></div><div class="mt-4 flex items-center gap-3"><button class="text-sm font-semibold text-blue-600" @click="selectAllVisible">Select all visible</button><span class="text-sm text-slate-500">{{selected.length}} selected</span><button :disabled="!selected.length||saving" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="addSelected">Add Selected</button></div><div class="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><label v-for="s in availableStudents" :key="s.id" class="flex cursor-pointer items-center gap-3 rounded-lg border p-3 hover:bg-slate-50"><input v-model="selected" type="checkbox" :value="s.id"><div><div class="font-semibold">{{s.first_name}} {{s.last_name}}</div><div class="text-sm text-slate-500">{{s.student_number||'No student #'}} · {{s.house?.name||'No house'}}</div></div></label><div v-if="!availableStudents.length" class="text-sm text-slate-500">No available students match these filters.</div></div></section></div></main></template>
